steps:
  - name: gcr.io/cloud-builders/npm
    id: install
    args:
      - install

 - name: gcr.io/cloud-builders/npm
    id: test
    args:
      - run
      - test

  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/nest-test:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - gcr.io/$PROJECT_ID/nest-test:$SHORT_SHA

  - name: gcr.io/cloud-builders/gcloud
    id: deploy
    args:
      - beta
      - run
      - deploy
      - nest-test
      - --image
      - gcr.io/$PROJECT_ID/nest-test:$SHORT_SHA
      - --platform
      - managed
      - --region
      - europe-west1
