# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: npm test

  build-deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    # dockerize
    # tag
    # push
    # deploy
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud docker --authorize-only
      - run: docker build --rm=false -t gcr.io/${GCLOUD_PROJECT_ID}/nest-test:$CIRCLE_SHA1 .
      - run: docker push gcr.io/${GCLOUD_PROJECT_ID}/nest-test:$CIRCLE_SHA1
      - run: gcloud beta run deploy nest-test --image gcr.io/${GCLOUD_PROJECT_ID}/nest-test:$CIRCLE_SHA1 --platform managed --region europe-west1 --allow-unauthenticated

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build-deploy:
          requires:
            - test
          filters:
            branches:
              only: master
